### ISSUE TITLE
README.md needs updated name of example file

### ISSUE THREAD

**Issue by danyork** [paulej/rfctools#2]
Paul,

In README.md the examples refer to 

`draft-jones-example-00.md` 

however the file in the 'example` directory is actually called:

`draft-jones-markdown-example-00.md`

I just copied your examples to try it out and was puzzled why it didn't work until I realized the file name needed to be updated.

**Comment by paulej** [comment]
Again, thanks for bringing that to my attention.  I fixed that problem, as well.  Let me know if I missed any.

**Comment by danyork** [comment]
Glad to help.
