### ISSUE TITLE
current state won't run as-is from your published docker image on OSX

### ISSUE THREAD

**Issue by geeohgeegeeoh** [paulej/rfctools#3]
$ make
docker run --rm --user=501:20 -v /Users/ggm/Projects/rfctools/example:/rfc -v /Users/ggm/.cache/xml2rfc:/var/cache/xml2rfc paulej/rfctools md2rfc draft-jones-markdown-example-00.md
Parsing file draft-jones-markdown-example-00.xml
ERROR: Unable to validate the XML document: draft-jones-markdown-example-00.xml
 <string>: Line 3: Syntax of value for attribute category of rfc is not valid
 <string>: Line 3: Value "" for attribute category of rfc is not among the enumerated set
make: *** [draft-jones-markdown-example-00.txt] Error 1
$

**Comment by paulej** [comment]
Did you build the docker image locally or pull down the one I built before? The old ones are now outdated, because mmark has changed. I forget to build a new public image!

**Comment by geeohgeegeeoh** [comment]
I pulled it down. I will retry with locally made or fresh from your pub
point if you have refreshed.

G

**Comment by paulej** [comment]
I just re-built the docker image and pushed it to Docker Hub, if you want to give it a try again.  This one should work.

**Comment by geeohgeegeeoh** [comment]
worked fine. please close the issue.
